version: '3.9'

services:
  mysqldb:
    image: mysql:5.7    
    container_name: mysql-db
    restart: unless-stopped
    networks:
      - compose-bridge
    environment:
      MYSQL_DATABASE: escola_ingles
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
      MYSQL_TCP_PORT: 3307
    ports:
    - 3307:3307
    volumes:
      - mysql_db:/var/lib/mysql 
  phpmyadmin:
    image: phpmyadmin
    container_name: php-my-admin
    links:
      - mysqldb
    environment:
      PMA_HOST: mysqldb
      PMA_PORT: 3307
      PMA_ARBITRARY: 1
    networks:
      - compose-bridge
    restart: unless-stopped
    ports:
      - 8081:80 
  app:
    build: .
    command: "npm start" 
    container_name: app-node-container
    restart: unless-stopped
    networks:
      - compose-bridge
    ports:
      - 3000:3000
    volumes:
      - .:/usr/app 
    depends_on:
      - mysqldb
networks:
  compose-bridge:
    driver: bridge
volumes: 
  mysql_db: